default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: "<%= ENV["DB_PASSWORD"] %>"
development:
  <<: *default
  database: timesheet

staging:
  <<: *default

production:
  <<: *default
  database: timesheet_production
